# fly.toml app configuration file generated for roofstacks on 2023-11-02T17:25:08+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "roofstacks"
primary_region = "cdg"

[build]
  dockerfile = "./Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
